[theme]
base = "dark"
primaryColor = "#fd570b"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
borderColor = "#30363D"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
baseRadius = "0.75rem"
buttonRadius = "0.5rem"
showWidgetBorder = true
headingFontWeights = [800, 700, 700, 600, 600, 600]
